require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/profits", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Profit. As you add validations to Profit, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Profit.create! valid_attributes
      get profits_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      profit = Profit.create! valid_attributes
      get profit_url(profit)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_profit_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      profit = Profit.create! valid_attributes
      get edit_profit_url(profit)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Profit" do
        expect {
          post profits_url, params: { profit: valid_attributes }
        }.to change(Profit, :count).by(1)
      end

      it "redirects to the created profit" do
        post profits_url, params: { profit: valid_attributes }
        expect(response).to redirect_to(profit_url(Profit.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Profit" do
        expect {
          post profits_url, params: { profit: invalid_attributes }
        }.to change(Profit, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post profits_url, params: { profit: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested profit" do
        profit = Profit.create! valid_attributes
        patch profit_url(profit), params: { profit: new_attributes }
        profit.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the profit" do
        profit = Profit.create! valid_attributes
        patch profit_url(profit), params: { profit: new_attributes }
        profit.reload
        expect(response).to redirect_to(profit_url(profit))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        profit = Profit.create! valid_attributes
        patch profit_url(profit), params: { profit: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested profit" do
      profit = Profit.create! valid_attributes
      expect {
        delete profit_url(profit)
      }.to change(Profit, :count).by(-1)
    end

    it "redirects to the profits list" do
      profit = Profit.create! valid_attributes
      delete profit_url(profit)
      expect(response).to redirect_to(profits_url)
    end
  end
end
